import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,signInAnonymously,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,doc,onSnapshot,runTransaction,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyBZr2HdwiVG-vE1T12BcKlmWOUCB7QYlMY",authDomain:"texas-hold-em-8b398.firebaseapp.com",projectId:"texas-hold-em-8b398",storageBucket:"texas-hold-em-8b398.firebasestorage.app",messagingSenderId:"647906482664",appId:"1:647906482664:web:d2f3ddea2a969156072c5d"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),money=n=>`$${Number(n||0).toLocaleString("zh-TW")}`,makeId=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`,clean=s=>s.trim().toUpperCase().replace(/[^A-Z0-9_-]/g,"").slice(0,24);
let user=null,roomData=null,roomCode="",isOwner=false,unsubscribe=null,viewerName="";
const buyinTotal=p=>(p.transactions||[]).reduce((s,t)=>s+Number(t.amount||0),0),currentGame=()=>roomData?.games?.find(g=>g.id===roomData.currentGameId)||null;
function setStatus(t){$("status").textContent=t}
async function createOrOpenOwnerRoom(code){const ref=doc(db,"rooms",code);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists()){const g={id:makeId(),startedAt:new Date().toISOString(),endedAt:null,players:[]};tx.set(ref,{code,ownerEmail:user.email,ownerUid:user.uid,currentGameId:g.id,games:[g],favorites:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});return}const d=snap.data();if(d.ownerEmail&&d.ownerEmail!==user.email)throw new Error("這個群組已有其他房主");tx.update(ref,{ownerEmail:user.email,ownerUid:user.uid,updatedAt:serverTimestamp()})})}
async function enterOwnerRoom(code){roomCode=clean(code);if(!roomCode)return alert("請輸入群組代碼");await createOrOpenOwnerRoom(roomCode);localStorage.setItem("ownerRoom",roomCode);subscribe()}
async function enterViewerRoom(code,name){roomCode=clean(code);viewerName=name.trim();if(!roomCode||!viewerName)return alert("請輸入名稱與群組代碼");localStorage.setItem("viewerRoom",roomCode);localStorage.setItem("viewerName",viewerName);subscribe()}
function subscribe(){if(unsubscribe)unsubscribe();setStatus("正在同步…");unsubscribe=onSnapshot(doc(db,"rooms",roomCode),snap=>{if(!snap.exists()){alert("找不到這個群組");return}roomData=snap.data();isOwner=!!user?.email&&roomData.ownerEmail===user.email;render();setStatus("已即時同步")},e=>{console.error(e);setStatus("同步失敗")})}
async function mutate(fn){if(!isOwner)return alert("只有房主可以修改");const ref=doc(db,"rooms",roomCode);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error("群組不存在");const data=structuredClone(snap.data());if(data.ownerEmail!==user.email)throw new Error("不是房主");fn(data);data.updatedAt=serverTimestamp();tx.set(ref,data)})}
async function addFavorite(){
  const n=$("favoriteName").value.trim();
  if(!n)return alert("請輸入常用玩家名稱");
  try{
    await mutate(d=>{
      d.favorites=d.favorites||[];
      if(d.favorites.includes(n))throw new Error("這位玩家已在常用名單");
      d.favorites.push(n);
    });
    $("favoriteName").value="";
  }catch(e){alert(e.message)}
}
async function removeFavorite(name){
  if(!confirm(`確定將「${name}」從常用玩家移除嗎？\n\n過去牌局與統計不會被刪除。`))return;
  await mutate(d=>{
    d.favorites=(d.favorites||[]).filter(n=>n!==name);
  });
}
function renderFavorites(){
  const list=$("favoriteList");
  if(!list)return;
  const names=[...(roomData?.favorites||[])].sort((a,b)=>a.localeCompare(b,"zh-Hant"));
  list.innerHTML=names.map(n=>`<div class="favorite-chip"><span>${n}</span><button class="danger tiny remove-favorite" data-name="${n.replace(/"/g,"&quot;")}">移除</button></div>`).join("")||"<p class='muted'>尚未設定常用玩家</p>";
  list.querySelectorAll(".remove-favorite").forEach(btn=>btn.onclick=()=>removeFavorite(btn.dataset.name));
}
async function addPlayer(){const n=$("playerName").value.trim()||$("favoriteSelect").value;if(!n)return;try{await mutate(d=>{const g=d.games.find(x=>x.id===d.currentGameId);if(g.players.some(p=>p.name===n))throw new Error("玩家已存在");g.players.push({id:makeId(),name:n,cashout:0,transactions:[]});d.favorites=d.favorites||[];if(!d.favorites.includes(n))d.favorites.push(n)});$("playerName").value=""}catch(e){alert(e.message)}}
const addBuyin=(pid,a)=>mutate(d=>{const p=d.games.find(x=>x.id===d.currentGameId).players.find(x=>x.id===pid);p.transactions.push({id:makeId(),amount:Number(a),at:new Date().toISOString(),by:user.displayName||user.email})});
const saveCashout=(pid,a)=>mutate(d=>{d.games.find(x=>x.id===d.currentGameId).players.find(x=>x.id===pid).cashout=Number(a||0)});
function deleteBuyin(pid,tid){if(!isOwner)return alert("只有房主可以刪除買入紀錄");if(!confirm("確定刪除這筆買入紀錄嗎？

刪除後會重新計算該玩家與本局統計。"))return;mutate(d=>{const p=d.games.find(x=>x.id===d.currentGameId).players.find(x=>x.id===pid);p.transactions=(p.transactions||[]).filter(t=>t.id!==tid)}).catch(e=>alert(e.message))}
function editBuyin(pid,tid,oldAmount){if(!isOwner)return alert("只有房主可以修改買入紀錄");const v=prompt("請輸入正確的買入金額",String(oldAmount));if(v===null)return;const amount=Number(v);if(!Number.isFinite(amount)||amount<=0)return alert("請輸入大於 0 的金額");mutate(d=>{const p=d.games.find(x=>x.id===d.currentGameId).players.find(x=>x.id===pid);const t=(p.transactions||[]).find(x=>x.id===tid);if(!t)throw new Error("找不到這筆買入紀錄");t.amount=amount;t.editedAt=new Date().toISOString();t.editedBy=user.displayName||user.email}).catch(e=>alert(e.message))}
function render(){if(!roomData)return;$("loginCard").classList.add("hidden");$("appArea").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");$("roleBanner").className=`role ${isOwner?"ownerrole":"viewerrole"}`;$("roleBanner").textContent=isOwner?"房主模式：妳可以編輯帳目":"觀看模式：只能查看帳目";document.querySelectorAll(".owner-only").forEach(x=>x.classList.toggle("hidden",!isOwner));$("roomTitle").textContent=`群組：${roomCode}`;const g=currentGame();$("gameDate").textContent=g?new Date(g.startedAt).toLocaleString("zh-TW",{hour12:false}):"";$("favoriteSelect").innerHTML='<option value="">常用玩家</option>'+[...(roomData.favorites||[])].sort().map(n=>`<option>${n}</option>`).join("");renderFavorites();const wrap=$("players");wrap.innerHTML="";(g?.players||[]).forEach(p=>{const f=$("playerTemplate").content.cloneNode(true),root=f.querySelector(".player"),b=buyinTotal(p),c=Number(p.cashout||0),profit=c-b;root.querySelector(".pname").textContent=p.name;root.querySelector(".pmeta").textContent=`${p.transactions.length} 次買入`;root.querySelector(".pbuy").textContent=money(b);root.querySelector(".pcash").textContent=money(c);const pe=root.querySelector(".pprofit");pe.textContent=`${profit>=0?"+":""}${money(profit)}`;pe.classList.add(profit>=0?"pos":"neg");root.querySelectorAll(".owner-control").forEach(x=>x.classList.toggle("hidden",!isOwner));root.querySelectorAll("[data-buy]").forEach(btn=>btn.onclick=()=>addBuyin(p.id,Number(btn.dataset.buy)));root.querySelector(".customBtn").onclick=()=>{const a=Number(prompt("輸入買入金額"));if(a>0)addBuyin(p.id,a)};root.querySelector(".saveBtn").onclick=()=>saveCashout(p.id,root.querySelector(".cashInput").value);root.querySelector(".deleteBtn").onclick=()=>confirm("確定刪除？")&&mutate(d=>{const gg=d.games.find(x=>x.id===d.currentGameId);gg.players=gg.players.filter(x=>x.id!==p.id)});root.querySelector(".txlist").innerHTML=(p.transactions||[]).slice().reverse().map(t=>`<li class="tx-row"><span>${new Date(t.at).toLocaleString("zh-TW",{hour12:false})}　<b>${money(t.amount)}</b>${t.editedAt?"（已修改）":""}</span>${isOwner?`<span class="tx-actions"><button class="secondary tiny edit-tx" data-tid="${t.id}" data-amount="${Number(t.amount||0)}">修改</button><button class="danger tiny delete-tx" data-tid="${t.id}">刪除</button></span>`:""}</li>`).join("")||"<li>尚無紀錄</li>";root.querySelectorAll(".edit-tx").forEach(btn=>btn.onclick=()=>editBuyin(p.id,btn.dataset.tid,btn.dataset.amount));root.querySelectorAll(".delete-tx").forEach(btn=>btn.onclick=()=>deleteBuyin(p.id,btn.dataset.tid));wrap.appendChild(f)});const b=(g?.players||[]).reduce((s,p)=>s+buyinTotal(p),0),c=(g?.players||[]).reduce((s,p)=>s+Number(p.cashout||0),0),d=c-b;$("totalBuyin").textContent=money(b);$("totalCashout").textContent=money(c);$("difference").textContent=`${d>0?"+":""}${money(d)}`;$("differenceHint").textContent=d===0?"帳目相符，可以安心結算。":d>0?`目前多出 ${money(d)}。`:`目前少了 ${money(Math.abs(d))}。`;renderReport();renderGameHistory()}

function gameMatchesRange(g,range,now){const d=new Date(g.startedAt);return range==="all"||range==="year"&&d.getFullYear()===now.getFullYear()||range==="month"&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}
function deleteGame(gameId){if(!isOwner)return alert("只有房主可以刪除牌局");const target=(roomData.games||[]).find(g=>g.id===gameId);if(!target)return;const when=new Date(target.startedAt).toLocaleString("zh-TW",{hour12:false});if(!confirm(`確定永久刪除 ${when} 的牌局嗎？\n\n刪除後無法復原，該局也會從月／年統計移除。`))return;mutate(d=>{d.games=(d.games||[]).filter(g=>g.id!==gameId);if(d.currentGameId===gameId){if(d.games.length){d.currentGameId=d.games[d.games.length-1].id}else{const g={id:makeId(),startedAt:new Date().toISOString(),endedAt:null,players:[]};d.games=[g];d.currentGameId=g.id}}}).catch(e=>alert(e.message))}
function renderGameHistory(){const box=$("gameHistory");if(!box)return;const range=$("range").value,now=new Date();const games=(roomData.games||[]).filter(g=>gameMatchesRange(g,range,now)).slice().sort((a,b)=>new Date(b.startedAt)-new Date(a.startedAt));box.innerHTML=games.map(g=>{const buy=(g.players||[]).reduce((s,p)=>s+buyinTotal(p),0),cash=(g.players||[]).reduce((s,p)=>s+Number(p.cashout||0),0),diff=cash-buy,isCurrent=g.id===roomData.currentGameId;return `<div class="game-row"><div><b>${new Date(g.startedAt).toLocaleString("zh-TW",{hour12:false})}</b><br><small>${g.players?.length||0} 位玩家・投入 ${money(buy)}・差額 ${diff>=0?"+":""}${money(diff)}${isCurrent?"・目前牌局":""}</small></div>${isOwner?`<button class="danger small delete-game" data-game-id="${g.id}">刪除此局</button>`:""}</div>`}).join("")||"<p class='muted'>尚無牌局紀錄</p>";box.querySelectorAll(".delete-game").forEach(btn=>btn.onclick=()=>deleteGame(btn.dataset.gameId))}

function renderReport(){const range=$("range").value,now=new Date(),map=new Map();(roomData.games||[]).filter(g=>{const d=new Date(g.startedAt);return range==="all"||range==="year"&&d.getFullYear()===now.getFullYear()||range==="month"&&d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}).forEach(g=>(g.players||[]).forEach(p=>{const r=map.get(p.name)||{games:0,buyin:0,cashout:0};r.games++;r.buyin+=buyinTotal(p);r.cashout+=Number(p.cashout||0);map.set(p.name,r)}));$("report").innerHTML=[...map].sort((a,b)=>(b[1].cashout-b[1].buyin)-(a[1].cashout-a[1].buyin)).map(([n,r])=>{const p=r.cashout-r.buyin;return`<div class="reportrow"><span><b>${n}</b><br><small>${r.games} 場・投入 ${money(r.buyin)}</small></span><b class="${p>=0?"pos":"neg"}">${p>=0?"+":""}${money(p)}</b></div>`}).join("")||"<p class='muted'>尚無資料</p>"}
$("googleBtn").onclick=async()=>{const provider=new GoogleAuthProvider();try{const r=await signInWithPopup(auth,provider);const c=prompt("請輸入妳要管理的群組代碼");if(c)await enterOwnerRoom(c)}catch(e){if(e.code?.includes("popup"))await signInWithRedirect(auth,provider);else alert(e.message)}};$("viewerBtn").onclick=async()=>{if(!auth.currentUser)await signInAnonymously(auth);await enterViewerRoom($("roomCode").value,$("viewerName").value)};$("addPlayerBtn").onclick=addPlayer;$("addFavoriteBtn").onclick=addFavorite;$("finishBtn").onclick=()=>mutate(d=>{d.games.find(x=>x.id===d.currentGameId).endedAt=new Date().toISOString()}).then(()=>alert("本局已完成，紀錄已保存。"));$("newGameBtn").onclick=()=>confirm("確定開新局？舊紀錄會保留。")&&mutate(d=>{const g={id:makeId(),startedAt:new Date().toISOString(),endedAt:null,players:[]};d.games.push(g);d.currentGameId=g.id});$("range").onchange=()=>{renderReport();renderGameHistory()};$("favoriteSelect").onchange=()=>$("playerName").value=$("favoriteSelect").value;$("switchBtn").onclick=()=>{localStorage.removeItem("ownerRoom");localStorage.removeItem("viewerRoom");location.reload()};$("logoutBtn").onclick=()=>signOut(auth).then(()=>location.reload());
onAuthStateChanged(auth,u=>{user=u;if(!u){setStatus("請登入");return}setStatus("已登入");const ownerRoom=localStorage.getItem("ownerRoom"),viewRoom=localStorage.getItem("viewerRoom"),vname=localStorage.getItem("viewerName")||"";if(u.email&&ownerRoom)enterOwnerRoom(ownerRoom).catch(e=>alert(e.message));else if(!u.email&&viewRoom)enterViewerRoom(viewRoom,vname)});getRedirectResult(auth).then(r=>{if(r?.user){user=r.user;const c=prompt("請輸入妳要管理的群組代碼");if(c)enterOwnerRoom(c)}});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");